"""initial schema

Revision ID: b184b6d3c681
Revises:
Create Date: 2026-08-25 00:03:34.374002

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.db.base import UTCTimestamp

revision: str = "b184b6d3c681"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("deleted_at", UTCTimestamp(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=48), nullable=False),
        sa.Column("object_type", sa.String(length=48), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_event_created", ["event_type", "created_at"], unique=False
        )
        batch_op.create_index("ix_audit_logs_user_created", ["user_id", "created_at"], unique=False)

    op.create_table(
        "cleanup_rules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("match_all", sa.Boolean(), nullable=False),
        sa.Column("conditions", sa.JSON(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cleanup_rules_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cleanup_rules")),
        sa.UniqueConstraint("user_id", "name", name="uq_rule_name_per_user"),
    )
    with op.batch_alter_table("cleanup_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cleanup_rules_user_id"), ["user_id"], unique=False)

    op.create_table(
        "mailboxes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("google_email_address", sa.String(length=320), nullable=False),
        sa.Column("history_id", sa.String(length=64), nullable=True),
        sa.Column("last_analysis_at", UTCTimestamp(), nullable=True),
        sa.Column("total_messages_cached", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_mailboxes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mailboxes")),
    )
    with op.batch_alter_table("mailboxes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mailboxes_user_id"), ["user_id"], unique=True)

    op.create_table(
        "oauth_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("google_sub", sa.String(length=64), nullable=False),
        sa.Column("google_email", sa.String(length=320), nullable=False),
        sa.Column("access_token_encrypted", sa.Text(), nullable=True),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=True),
        sa.Column("token_expires_at", UTCTimestamp(), nullable=True),
        sa.Column("last_refreshed_at", UTCTimestamp(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("connected_at", UTCTimestamp(), nullable=False),
        sa.Column("revoked_at", UTCTimestamp(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_oauth_connections_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_connections")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_oauth_connections_google_sub")),
    )
    with op.batch_alter_table("oauth_connections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_connections_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_connections_user_id"), ["user_id"], unique=True)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", UTCTimestamp(), nullable=False),
        sa.Column("revoked_at", UTCTimestamp(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("messages_total", sa.Integer(), nullable=True),
        sa.Column("messages_processed", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.String(length=512), nullable=True),
        sa.Column("dispatcher_task_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", UTCTimestamp(), nullable=True),
        sa.Column("completed_at", UTCTimestamp(), nullable=True),
        sa.Column("cancelled_at", UTCTimestamp(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["mailboxes.id"],
            name=op.f("fk_analysis_jobs_mailbox_id_mailboxes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_analysis_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_jobs_mailbox_status", ["mailbox_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_analysis_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "cleanup_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column("approved_at", UTCTimestamp(), nullable=True),
        sa.Column("execution_started_at", UTCTimestamp(), nullable=True),
        sa.Column("completed_at", UTCTimestamp(), nullable=True),
        sa.Column("cancelled_at", UTCTimestamp(), nullable=True),
        sa.Column("failure_summary", sa.JSON(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["mailboxes.id"],
            name=op.f("fk_cleanup_plans_mailbox_id_mailboxes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_cleanup_plans_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cleanup_plans")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_plan_idempotency_per_user"),
    )
    with op.batch_alter_table("cleanup_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_cleanup_plans_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_cleanup_plans_user_status", ["user_id", "status"], unique=False)

    op.create_table(
        "email_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("primary_sender_domain", sa.String(length=255), nullable=True),
        sa.Column("primary_category", sa.String(length=48), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("first_message_at", UTCTimestamp(), nullable=True),
        sa.Column("last_message_at", UTCTimestamp(), nullable=True),
        sa.Column("sample_subjects", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["mailboxes.id"],
            name=op.f("fk_email_groups_mailbox_id_mailboxes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_groups")),
        sa.UniqueConstraint("mailbox_id", "group_key", name="uq_group_key_per_mailbox"),
    )
    with op.batch_alter_table("email_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_groups_mailbox_id"), ["mailbox_id"], unique=False
        )

    op.create_table(
        "email_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=64), nullable=False),
        sa.Column("gmail_thread_id", sa.String(length=64), nullable=True),
        sa.Column("sender_email", sa.String(length=320), nullable=True),
        sa.Column("sender_name", sa.String(length=255), nullable=True),
        sa.Column("sender_domain", sa.String(length=255), nullable=True),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("received_at", UTCTimestamp(), nullable=True),
        sa.Column("size_estimate", sa.Integer(), nullable=True),
        sa.Column("has_attachments", sa.Boolean(), nullable=False),
        sa.Column("attachment_count", sa.Integer(), nullable=False),
        sa.Column("is_starred", sa.Boolean(), nullable=False),
        sa.Column("is_important", sa.Boolean(), nullable=False),
        sa.Column("has_list_unsubscribe", sa.Boolean(), nullable=False),
        sa.Column("label_ids", sa.JSON(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["email_groups.id"],
            name=op.f("fk_email_messages_group_id_email_groups"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["mailboxes.id"],
            name=op.f("fk_email_messages_mailbox_id_mailboxes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_messages")),
        sa.UniqueConstraint("mailbox_id", "gmail_message_id", name="uq_gmail_message_per_mailbox"),
    )
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_email_messages_mailbox_domain", ["mailbox_id", "sender_domain"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_messages_mailbox_id"), ["mailbox_id"], unique=False
        )
        batch_op.create_index(
            "ix_email_messages_mailbox_received", ["mailbox_id", "received_at"], unique=False
        )

    op.create_table(
        "classifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("source", sa.String(length=8), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("risk", sa.String(length=16), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("ai_reasoning", sa.Text(), nullable=True),
        sa.Column("classifier_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_messages.id"],
            name=op.f("fk_classifications_message_id_email_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classifications")),
    )
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_classifications_message_id"), ["message_id"], unique=True
        )

    op.create_table(
        "cleanup_plan_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("gmail_message_id", sa.String(length=64), nullable=False),
        sa.Column("subject_snapshot", sa.String(length=500), nullable=True),
        sa.Column("sender_snapshot", sa.String(length=320), nullable=True),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("item_status", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.String(length=512), nullable=True),
        sa.Column("executed_at", UTCTimestamp(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_messages.id"],
            name=op.f("fk_cleanup_plan_items_message_id_email_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["cleanup_plans.id"],
            name=op.f("fk_cleanup_plan_items_plan_id_cleanup_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cleanup_plan_items")),
        sa.UniqueConstraint("plan_id", "message_id", name="uq_plan_item_message"),
    )
    with op.batch_alter_table("cleanup_plan_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cleanup_plan_items_message_id"), ["message_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cleanup_plan_items_plan_id"), ["plan_id"], unique=False
        )
        batch_op.create_index("ix_plan_items_plan_status", ["plan_id", "item_status"], unique=False)

    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("mailbox_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("risk", sa.String(length=16), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("contributing_rule_ids", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["mailbox_id"],
            ["mailboxes.id"],
            name=op.f("fk_recommendations_mailbox_id_mailboxes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_messages.id"],
            name=op.f("fk_recommendations_message_id_email_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_recommendations_mailbox_action", ["mailbox_id", "action"], unique=False
        )
        batch_op.create_index(
            "ix_recommendations_mailbox_status_risk", ["mailbox_id", "status", "risk"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_message_id"), ["message_id"], unique=True
        )

    op.create_table(
        "user_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("context", sa.String(length=16), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", UTCTimestamp(), nullable=False),
        sa.Column("updated_at", UTCTimestamp(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["email_messages.id"],
            name=op.f("fk_user_decisions_message_id_email_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["cleanup_plans.id"],
            name=op.f("fk_user_decisions_plan_id_cleanup_plans"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_decisions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_decisions")),
        sa.UniqueConstraint("user_id", "message_id", name="uq_decision_per_message"),
    )
    with op.batch_alter_table("user_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_decisions_message_id"), ["message_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_decisions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_decisions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_decisions_message_id"))

    op.drop_table("user_decisions")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_message_id"))
        batch_op.drop_index("ix_recommendations_mailbox_status_risk")
        batch_op.drop_index("ix_recommendations_mailbox_action")

    op.drop_table("recommendations")
    with op.batch_alter_table("cleanup_plan_items", schema=None) as batch_op:
        batch_op.drop_index("ix_plan_items_plan_status")
        batch_op.drop_index(batch_op.f("ix_cleanup_plan_items_plan_id"))
        batch_op.drop_index(batch_op.f("ix_cleanup_plan_items_message_id"))

    op.drop_table("cleanup_plan_items")
    with op.batch_alter_table("classifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classifications_message_id"))

    op.drop_table("classifications")
    with op.batch_alter_table("email_messages", schema=None) as batch_op:
        batch_op.drop_index("ix_email_messages_mailbox_received")
        batch_op.drop_index(batch_op.f("ix_email_messages_mailbox_id"))
        batch_op.drop_index("ix_email_messages_mailbox_domain")

    op.drop_table("email_messages")
    with op.batch_alter_table("email_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_groups_mailbox_id"))

    op.drop_table("email_groups")
    with op.batch_alter_table("cleanup_plans", schema=None) as batch_op:
        batch_op.drop_index("ix_cleanup_plans_user_status")
        batch_op.drop_index(batch_op.f("ix_cleanup_plans_user_id"))

    op.drop_table("cleanup_plans")
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_status"))
        batch_op.drop_index("ix_analysis_jobs_mailbox_status")

    op.drop_table("analysis_jobs")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_token_hash"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("oauth_connections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_connections_user_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_connections_status"))

    op.drop_table("oauth_connections")
    with op.batch_alter_table("mailboxes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mailboxes_user_id"))

    op.drop_table("mailboxes")
    with op.batch_alter_table("cleanup_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cleanup_rules_user_id"))

    op.drop_table("cleanup_rules")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_user_created")
        batch_op.drop_index("ix_audit_logs_event_created")

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
